### ISSUE TITLE
Module not found: Error: Can't resolve 'immer'

### ISSUE THREAD

**Issue by Tzvetelin88** [nartc/nartc-workspace#8]
When I started using ngrx-slice for the very first time, everything was working fine, and all dependencies were installed correctly.
After the second time I installed all packages (with yarn) from package.json (in this order ngrx-slice), I received this error:
```
Error: node_modules/ngrx-slice/lib/typings.d.ts:2:28 - error TS2307: Cannot find module 'immer' or its corresponding type declarations.

2 import type { Draft } from 'immer';
                             ~~~~~~~
```

I tried to delete node_modules and install all packages again. The same issue. I also removed ".angular", "yarn.lock" and same issue.

To solve this problem I just added immer:
```
yarn add immer
```

Is there something that I miss?

**Comment by nartc** [comment]
This is expected since `immer` is listed as `peerDependencies` instead of `dependencies` 
 https://github.com/nartc/nartc-workspace/tree/main/packages/ngrx-slice#peer-dependencies. This is to ensure the consumers (you) install `immer` and can also consume utilities from `immer` library in a straight-forward way (good DX with auto importing etc...)
